### ISSUE TITLE
Forside - HTML - IMG

### ISSUE THREAD

**Issue by Emsenparry** [Emsenparry/Misse-side-opgave#6]
Der skal være et billede af en kat på forsiden.

**Comment by Emsenparry** [comment]
Done.

**Comment by GyunaydanLyutvi** [comment]
@Emsenparry  Hvilket tag har du bruget til at link billedet ind?

**Comment by Emsenparry** [comment]
Jeg har bare brugt IMG tagget til at få billederne ind med. Hvis det er billedet på forsiden, så ligger den inde i en div. Du kan kigge på koden som ligger under ''Code'' menuen her i github. :D

**Comment by Emsenparry** [comment]
Klassen hedder ''div-one''

**Comment by Emsenparry** [comment]
Jeg har lige skiftet navnet på klassen fordi det ik giver mening. Klassen hedder derfor ''Image-one''

**Comment by GyunaydanLyutvi** [comment]
> Jeg har bare brugt IMG tagget til at få billederne ind med. Hvis det er billedet på forsiden, så ligger den inde i en div. Du kan kigge på koden som ligger under ''Code'' menuen her i github. :D

jeg har lige fandt det ude af :d
